### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by ghaiklor** [eknkc/babel-preset-async-to-bluebird#1]
When running transpiled code I'm facing the following:

```
/Users/ghaiklor/Library/Projects/kittik/lib/loader/Loader.js:24
      var ref = (0, _bluebird.coroutine)(regeneratorRuntime.mark(function _callee() {
                                         ^

ReferenceError: regeneratorRuntime is not defined
    at /Users/ghaiklor/Library/Projects/kittik/lib/loader/Loader.js:24:42
    at /Users/ghaiklor/Library/Projects/kittik/lib/loader/Loader.js:43:7
    at Object.<anonymous> (/Users/ghaiklor/Library/Projects/kittik/lib/loader/Loader.js:91:3)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/ghaiklor/Library/Projects/kittik/lib/bin/kittik.js:16:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
```

How can I fix that?

**Comment by fritx** [comment]
I use this: `import 'babel-polyfill'` in babel 6 system
